// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  // Example binding types:
  // - KV: KVNamespace
  // - Durable Object: DurableObjectNamespace
  // - D1: D1Database
  // - R2: R2Bucket
  
  // Assets binding (automatically configured by wrangler)
  ASSETS: Fetcher;
  
  // Add your environment variables here
  // AUTH_SECRET?: string;
  // AUTH_GOOGLE_ID?: string;
  // AUTH_GOOGLE_SECRET?: string;
}
